name: CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  flake-check:
    name: Flake Check
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - run: nix flake check

  build-hosts:
    name: Build Hosts
    runs-on: self-hosted
    needs: flake-check

    steps:
      - uses: actions/checkout@v4
      - run: |
          nix build .#nixosConfigurations.portuus.config.system.build.toplevel
          nix build .#nixosConfigurations.edge.config.system.build.toplevel
